### ISSUE TITLE
Disassembler Tasks

### ISSUE THREAD

**Issue by HawaiinPizza** [Ciaxur/yagb-emu#2]
**Implement CPU Instruction Set**
Through the use of the Resources, output the disassembled asm instructions of given ROM.

Tasks split up into, ([Op Table](https://gbdev.io/gb-opcodes//optables/))

- [ ] Column `x0 through x4` Chad
- [ ] Column `x5 through x9` Zak
- [x] Column `xA through xF` Omar^2

**Comment by Ciaxur** [comment]
**CPU Instruction Set Task**
Columns `xA through xF` Committed in this [Commit](https://github.com/Ciaxur/yagb-emu/commit/eaf4d7cd05f0f7817c75d684bb8f121e69313c04) :smiley:

**Comment by HawaiinPizza** [comment]
We did it boys

**Comment by Ciaxur** [comment]
Not quite yet. We still need to get the actual 8bit and 16bit data and address values from the hexdump indicated as,

`d8` immediate 8-bit data
`d16` immediate 16-bit data
`a8` 8-bit unsigned data
`a16` 16-bit address
`r8` 8-bit signed data

**Comment by Ciaxur** [comment]
[Restarting Development](https://github.com/Ciaxur/yagb-emu/commit/e8fb9e37) with a plan and structure. Jumped in to coding way too soon 😂 #
